site_name: PromptDiff
site_description: Enterprise LLM Prompt Regression Testing & Cost/Latency Gating
site_author: PromptDiff Team
repo_url: https://github.com/latryee/promptdiff
repo_name: latryee/promptdiff
docs_dir: docs_src

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Overview: index.md
  - CLI Reference: api/cli.md
  - Python SDK: api/sdk.md
  - Recipes: recipes.md
  - Architecture: architecture.md
  - Security & Sandbox: security.md
  - ⚡ Live Playground: "https://latryee.github.io/promptdiff/"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
