"""promptdiff: Enterprise-grade LLM Prompt & Model Regression Testing Framework."""

import sys

# Ensure UTF-8 console output on Windows to prevent UnicodeEncodeError on international codepages
if sys.platform == "win32":
    try:
        if hasattr(sys.stdout, "reconfigure"):
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        if hasattr(sys.stderr, "reconfigure"):
            sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

__version__ = "3.4.0"
__author__ = "promptdiff team"

from promptdiff.core.db import TelemetryDatabase
from promptdiff.core.exceptions import (
    CacheError,
    ConfigurationError,
    DatasetLoadError,
    EvaluatorExecutionError,
    PromptDiffError,
    ProviderExecutionError,
    RunnerError,
)
from promptdiff.core.models import (
    ArenaReport,
    ComparisonResult,
    ConversationVersion,
    DiffReport,
    MultiComparisonResult,
    PromptVersion,
    RegressionVerdict,
    RunResult,
    TestCase,
)
from promptdiff.sdk import (
    analyze_cache_impact,
    async_compare,
    attack_tree,
    attribute_hallucinations,
    benchmark_needle_matrix,
    benchmark_reflexion,
    cache_sim,
    canary,
    cascade,
    cascaded_judge,
    compare,
    compile_prompt,
    compliance_audit,
    compute_bradley_terry_ratings,
    compute_elo_ratings,
    council,
    detect_drift,
    detect_schema_breaking_changes,
    detect_watermark,
    diff_ast,
    distill,
    edge_quant,
    export_bundle,
    export_executive_report,
    export_notebook,
    fuzz,
    generate_hard_negatives,
    history,
    inspect_watermark,
    launch_studio,
    lsp_diagnostics,
    mcts_optimize,
    mutate,
    mutation_score,
    optimize,
    optimize_prefix_cache,
    personas,
    profile_stream,
    profile_streaming,
    property_test,
    reflex_benchmark,
    saliency,
    saliency_heatmap,
    sanitize_input,
    scaffold_editor_extensions,
    select_exemplars_mmr,
    shadow_replay,
    shrink,
    simulate_cascade,
    sla_stress,
    synthesize_dpo,
    test_hypothesis,
    tune,
    verify_watermark,
    watermark,
)

__all__ = [
    "ArenaReport",
    "CacheError",
    "ComparisonResult",
    "ConfigurationError",
    "ConversationVersion",
    "DatasetLoadError",
    "DiffReport",
    "EvaluatorExecutionError",
    "MultiComparisonResult",
    "PromptDiffError",
    "PromptVersion",
    "ProviderExecutionError",
    "RegressionVerdict",
    "RunnerError",
    "RunResult",
    "TestCase",
    "TelemetryDatabase",
    "analyze_cache_impact",
    "async_compare",
    "compare",
    "optimize",
    "tune",
    "shrink",
    "fuzz",
    "cache_sim",
    "mutate",
    "history",
    "export_bundle",
    "shadow_replay",
    "cascade",
    "cascaded_judge",
    "compute_bradley_terry_ratings",
    "compute_elo_ratings",
    "canary",
    "detect_schema_breaking_changes",
    "sla_stress",
    "personas",
    "saliency",
    "distill",
    "mutation_score",
    "lsp_diagnostics",
    "council",
    "profile_stream",
    "watermark",
    "inspect_watermark",
    "edge_quant",
    "property_test",
    "compliance_audit",
    "reflex_benchmark",
    "export_notebook",
    "compile_prompt",
    "mcts_optimize",
    "attribute_hallucinations",
    "attack_tree",
    "profile_streaming",
    "simulate_cascade",
    "launch_studio",
    "test_hypothesis",
    "generate_hard_negatives",
    "synthesize_dpo",
    "select_exemplars_mmr",
    "saliency_heatmap",
    "optimize_prefix_cache",
    "detect_drift",
    "diff_ast",
    "sanitize_input",
    "detect_watermark",
    "benchmark_reflexion",
    "benchmark_needle_matrix",
    "scaffold_editor_extensions",
    "export_executive_report",
    "verify_watermark",
    "__version__",
]
