"""promptdiff: Enterprise-grade LLM Prompt & Model Regression Testing Framework."""

__version__ = "3.0.0"
__author__ = "promptdiff team"

from promptdiff.core.models import (
    ArenaReport,
    ComparisonResult,
    DiffReport,
    MultiComparisonResult,
    PromptVersion,
    RegressionVerdict,
    RunResult,
    TestCase,
)
from promptdiff.sdk import (
    async_compare,
    cache_sim,
    canary,
    cascade,
    compare,
    distill,
    export_bundle,
    fuzz,
    history,
    lsp_diagnostics,
    mutate,
    mutation_score,
    optimize,
    personas,
    saliency,
    shadow_replay,
    shrink,
    sla_stress,
    tune,
)

__all__ = [
    "ArenaReport",
    "ComparisonResult",
    "DiffReport",
    "MultiComparisonResult",
    "PromptVersion",
    "RegressionVerdict",
    "RunResult",
    "TestCase",
    "async_compare",
    "compare",
    "optimize",
    "tune",
    "shrink",
    "fuzz",
    "cache_sim",
    "mutate",
    "history",
    "export_bundle",
    "shadow_replay",
    "cascade",
    "canary",
    "sla_stress",
    "personas",
    "saliency",
    "distill",
    "mutation_score",
    "lsp_diagnostics",
    "__version__",
]
