"""promptdiff: Enterprise-grade LLM Prompt & Model Regression Testing Framework."""

__version__ = "3.4.0"
__author__ = "promptdiff team"

from promptdiff.core.models import (
    ArenaReport,
    ComparisonResult,
    DiffReport,
    MultiComparisonResult,
    PromptVersion,
    RegressionVerdict,
    RunResult,
    TestCase,
)
from promptdiff.sdk import (
    async_compare,
    cache_sim,
    canary,
    cascade,
    compare,
    compile_prompt,
    compliance_audit,
    council,
    distill,
    edge_quant,
    export_bundle,
    export_notebook,
    fuzz,
    history,
    inspect_watermark,
    lsp_diagnostics,
    mutate,
    mutation_score,
    optimize,
    personas,
    profile_stream,
    property_test,
    reflex_benchmark,
    saliency,
    shadow_replay,
    shrink,
    sla_stress,
    tune,
    watermark,
)

__all__ = [
    "ArenaReport",
    "ComparisonResult",
    "DiffReport",
    "MultiComparisonResult",
    "PromptVersion",
    "RegressionVerdict",
    "RunResult",
    "TestCase",
    "async_compare",
    "compare",
    "optimize",
    "tune",
    "shrink",
    "fuzz",
    "cache_sim",
    "mutate",
    "history",
    "export_bundle",
    "shadow_replay",
    "cascade",
    "canary",
    "sla_stress",
    "personas",
    "saliency",
    "distill",
    "mutation_score",
    "lsp_diagnostics",
    "council",
    "profile_stream",
    "watermark",
    "inspect_watermark",
    "edge_quant",
    "property_test",
    "compliance_audit",
    "reflex_benchmark",
    "export_notebook",
    "compile_prompt",
    "__version__",
]
